name: proj-one
on:
  push:
    paths:
      - "projects/proj-one/**"
      - .github/workflows/proj-one.yml
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: projects/proj-one
          start: npm start
