name: ProjOne E2E
on:
  push:
    paths:
      - "projects/proj-one/**"
  pull_request:
    paths:
      - "projects/proj-one/**"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
