name: ProjOne E2E
on:
  push:
    paths:
      - "projects/proj-one/**"
      - .github/workflows/test.yml
  pull_request:
    paths:
      - "projects/proj-one/**"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          project: projects/proj-one
          uses: actions/checkout@v2
          start: npm start
